### ISSUE TITLE
Tracker fails to load on first run - Lua Exception

### ISSUE THREAD

**Issue by UTDZac** [besteon/Ironmon-Tracker#68] opened 2022-06-03 22:24 UTC
From IronMON Discord: "when loading the .lua... Ironmon-Tracker v0.3.0 NLua.Exceptions.LuaScriptException: A,B,Start,Select"

This has been an ongoing issue for many versions of the tracker, including the latest 3.0.0. Several people each day report this issue. In almost all cases it can be resolved by closing everything and reopening a few times.

I'm assuming the tracker has to initiate some files on first load, but might do so in the wrong order and is unable to find the files when you first run it; hence why closing and opening again fixes it. Is this something that can be resolved, or can a more detailed message be included in the error to instruct the user to restart?

**Comment by bdjeffyp** [comment] 2022-06-04 01:55
Thanks, UTDZac. We can take a look and see if we can repro to find the cause of why it is happening.

**Comment by Tapollo** [comment] 2022-06-04 02:02
@bdjeffyp I have encountered this too. the Lua Console says:

![image](https://user-images.githubusercontent.com/104585947/171972348-4de0dffe-7e60-467b-b86f-ea5259bf6bbe.png)

**Comment by Fellshadow** [comment] 2022-06-04 02:56
I'll also note here in that i've seen some cases where just closing and re-opening didn't fix the issue for them but sometimes it was something to do with their Settings.ini file. At other times when I asked for the full lua console output it was indeed occurring at the point the tracker was loading files, so it's most likely relating to that as UTDZac says.

One user I remember it wouldn't work unless they provided a folder for `ROMS_FOLDER` (just leaving it as `ROMS_FOLDER=` as it is on initial download wasn't working) and another had to include a space after the `ROMS_FOLDER=` before their folder path for it to work. Both seemingly arbitrary things that happened to fix the issue for them.

**Comment by bdjeffyp** [comment] 2022-06-04 03:37
@UTDZac, I have done some testing on a different PC, making folders with fresh installs and have been reproing the issue. In many instances, I can avoid the issue altogether if I start BizHawk, immediately close it, reopen it again and start the game and tracker. The tracker loads just fine in that instance. The only difference I can see between a new install and an install that has been opened at least once is the presence of a `config.ini` file that BizHawk autogenerates after it's first run. Your guess is as good as mine as to why this works... Ultimately, I believe the root issue is not the tracker, but BizHawk not being properly configured until it's first run is completed. I will update the directions to make that recommendation to people.

@Fellshadow, regarding your comment, I am baffled by the whole `ROMS_FOLDER` thing. It doesn't make a lot of sense what is happening there. At this point, I am beginning to suspect that using INI files is causing more issues than not. Part of the reason I made the settings menu within the tracker is because of all the problems people have been having just editing the damn thing. If I can come up with a good solution for configuring the controller settings within the tracker's settings menu, it may solve all of these problems because then the tracker is formatting the Settings.ini file in a way that would be device agnostic and without potential human error.

@Tapollo, your error looks like something else entirely. Can you make a new issue along with some steps on how you came to get that error?

**Comment by bdjeffyp** [comment] 2022-06-04 03:50
Okay, I added a "step 0" to the Installation procedure in the README in PR #69 (nice). It clarifies that users who are using BizHawk for the first time must open and close it once before trying to use the tracker. This workaround isn't perfect, but it is a start. I'll work on getting @besteon to approve and merge, since I can't outright merge without a review. 

@UTDZac, would you be able to update docs in the Discord to have new BizHawk users open and close the app on their first run before attempting to use the tracker, please?

**Comment by Fellshadow** [comment] 2022-06-04 13:34
> @Fellshadow, regarding your comment, I am baffled by the whole `ROMS_FOLDER` thing. It doesn't make a lot of sense what is happening there. At this point, I am beginning to suspect that using INI files is causing more issues than not. Part of the reason I made the settings menu within the tracker is because of all the problems people have been having just editing the damn thing. If I can come up with a good solution for configuring the controller settings within the tracker's settings menu, it may solve all of these problems because then the tracker is formatting the Settings.ini file in a way that would be device agnostic and without potential human error.

I am also just as baffled, though the cases where it only worked when they edited their Settings.ini were very few. If the true culprit is bizhawk's config.ini it could be possible that maybe the config.ini got made somewhere between their fiddling with the Settings.ini? It's tough to say whether they actually closed bizhawk fully when talking about the issue in a discord text channel of course.

**Comment by UTDZac** [comment] 2022-06-17 19:26
Trying again on latest (0.3.5), I can no longer reproduce this issue by removing my config.ini file from Bizhawk. Seems to work fine on versions 0.3.3 and up. I suspect the changes to how we handled the Settings.ini parsing have helped resolve this?

![image](https://user-images.githubusercontent.com/4258818/174388280-ae4894fe-35f4-4ca0-bf9c-40106a0361df.png)

I am able to continue on and play the game normally. The tracker works fine and shows data.

**Comment by bdjeffyp** [comment] 2022-06-18 17:43
This is great news! I'll go ahead and close this issue as resolved. If people are experiencing any new errors associated with starting the tracker, let's make a new issue. Thanks all for the efforts to make this fix happen!!

**Closed** 2022-06-18 17:43 UTC
Labels: Bug
